### ISSUE TITLE
我将sion.h导入自己的项目会报这个错误

### ISSUE THREAD

**Issue by sherppard** [zanllp/Sion#1]
错误	C2664	
“std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)”: 无法将参数 1 从“_Ty”转换为“std::initializer_list<_Elem>”
WeChatHelper	c:\users\sion.h	19

**Comment by zanllp** [comment]
MyString a = 'a'; 会报那个错误
MyString a = “a”; 不会
在编译时才报错是因为MyString使用了forward<T>来转发构造函数
