### ISSUE TITLE
无法发送请求

### ISSUE THREAD

**Issue by wgywgy** [zanllp/Sion#14]
代码：
    auto resp = sion::Request()
                .SetUrl("http://httpbin.org/get")
                .SetHttpMethod(sion::Method::Post)
                .SetBody(R"({"data": 233333,"msg":"hello world!"})")
                .SetHeader("Content-Type", "application/json; charset=utf-8")
                .Send();
    std::cout << resp.StrBody() << std::endl;
    std::cout << "done \n";
结果：
![截屏2022-02-10 下午12 05 06](https://user-images.githubusercontent.com/2408246/153335304-2be75b49-755d-4add-ba66-e26f72ad3d5d.png)

描述：
使用sion发送Post请求，charles 抓包，发现请求地址有问题。没有请求成功

**Comment by zanllp** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/25872019/153336002-ec37e0a3-fb8c-4ff1-981c-d6200baceee7.png">
我这看起来好像是正常的，你是什么环境

**Comment by zanllp** [comment]
这是url改成post的
<img width="736" alt="image" src="https://user-images.githubusercontent.com/25872019/153336464-94755ad6-ca6c-4fbd-a583-83a32e770b4c.png">

**Comment by wgywgy** [comment]
我是mac 环境，用xcode编译的

**Comment by zanllp** [comment]
我有时间看看是什么问题，这边测试linux下是gcc, mac下是clang都用的cmake。win下是vs2019。确保所有例子能跑通的

**Comment by zanllp** [comment]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/25872019/153355538-c513526c-8829-4571-a7a0-041b6617036b.png">
没问题啊，考虑是不是其他因素，尝试把charles关掉

**Comment by wgywgy** [comment]
我试了关掉Charles可以，开Charles，或者ClashX 就不行了

**Comment by wgywgy** [comment]
错误截图：
![截屏2022-02-10 下午4 28 01](https://user-images.githubusercontent.com/2408246/153367575-61ec695b-a122-4522-a9c8-a003afa4ce1f.png)

**Comment by zanllp** [comment]
好奇怪的问题，我晚上回家再看，感觉应该是可以的。我的vpn是bywave没遇到这种问题

**Comment by zanllp** [comment]
> 错误截图： ![截屏2022-02-10 下午4 28 01](https://user-images.githubusercontent.com/2408246/153367575-61ec695b-a122-4522-a9c8-a003afa4ce1f.png)

是开Charles或者ClashX时请求，就会报400吗？

正常charles和vpn应该是不对sion造成影响才对，就跟node和curl没法直接请求google一样,得加代理

**Comment by wgywgy** [comment]
开ClashX 报400，charles是503
![截屏2022-02-11 上午11 45 46](https://user-images.githubusercontent.com/2408246/153534624-53b40b85-c0cb-4697-9d75-b37c0b48fa62.png)

**Comment by zanllp** [comment]
http支持代理了，你请求增加一个代理参数即使开着clashx和charles应该也正常了。
https过于复杂，文档又很少暂时实现不了。

你可以在 #15 里面获取到新的sion   这个pr我暂时不会合并
用法参考：
https://github.com/zanllp/sion/blob/a8505b8697aa34a3ef7814b31ffefd1590fbeb17/src/main.cc#L91-L96

你这种情况现在看起来依旧奇怪，感觉像是那些网络io的函数被hook了一样
