### ISSUE TITLE
异步方法回调不生效

### ISSUE THREAD

**Issue by zii4914** [zanllp/Sion#26]
![image](https://github.com/zanllp/sion/assets/34887749/d02ede73-cafd-42a9-8eba-b98376f2897d)
![image](https://github.com/zanllp/sion/assets/34887749/36a0b668-b0cb-4686-a75f-0505882d8c57)
这是我写的一个简单请求，使用await可以正常请求，但是使用回调没有得到结果

**Comment by zanllp** [comment]
是不是服务端的响应回来之前主线程就退出了。你可以阻塞下看看，我试了是正常的
![image](https://github.com/zanllp/sion/assets/25872019/63869e3b-aa9a-42b2-9449-1cd6da685eaf)

**Comment by zii4914** [comment]
我是个C++新手，好像是因为我类的单例导致的，放在private里面的话，就可以调起一次，后面就提示一个实例只能star一次。应该是Async实例声明存在问题导致的。
