### ISSUE TITLE
ubuntu下gcc编译会报错

### ISSUE THREAD

**Issue by Boreal** [zanllp/Sion#7]
ubuntu下gcc编译会报错

**Comment by zanllp** [comment]
贴下报错信息，我这个版本没问题的
![image](https://user-images.githubusercontent.com/25872019/117386537-ae679800-af19-11eb-80a7-ab1612f77780.png)

**Comment by Boreal** [comment]
![1620352584(1)](https://user-images.githubusercontent.com/39616624/117386991-862c6900-af1a-11eb-875d-1d0f24695d85.jpg)

**Comment by Boreal** [comment]
我用的是qt，跟这个有关系么，或者是还需要什么依赖库

**Comment by Boreal** [comment]
> 贴下报错信息，我这个版本没问题的
> ![image](https://user-images.githubusercontent.com/25872019/117386537-ae679800-af19-11eb-80a7-ab1612f77780.png)

我用的是qt，跟这个有关系么，或者是还需要什么依赖库

**Comment by zanllp** [comment]
> > 贴下报错信息，我这个版本没问题的
> > ![image](https://user-images.githubusercontent.com/25872019/117386537-ae679800-af19-11eb-80a7-ab1612f77780.png)
> 
> 我用的是qt，跟这个有关系么，或者是还需要什么依赖库

没依赖其他库，只要求c++11及以上就行。
qt应该也没问题。
这看起来应该是一个在链接时发生的错误，感觉可能是代码组织有点问题，可以尝试减少对sion的include到只剩一个文件先看看能不能编译完成试试

**Comment by Boreal** [comment]
> > > 贴下报错信息，我这个版本没问题的
> > > ![image](https://user-images.githubusercontent.com/25872019/117386537-ae679800-af19-11eb-80a7-ab1612f77780.png)
> > 
> > 
> > 我用的是qt，跟这个有关系么，或者是还需要什么依赖库
> 
> 没依赖其他库，只要求c++11及以上就行。
> qt应该也没问题。
> 这看起来应该是一个在链接时发生的错误，感觉可能是代码组织有点问题，可以尝试减少对sion的include到只剩一个文件先看看能不能编译完成试试

我新建的一个空项目，只要include <sion.h>就会报错，注释掉之后就可以正常运行

**Comment by zanllp** [comment]
给个能复现的demo和编译参数看看？
这个问题我还真没遇到过

**Comment by Boreal** [comment]
> 给个能复现的demo和编译参数看看？
> 这个问题我还真没遇到过

我在Linux和Windows下的qt5.12.10都无法直接编译，在vs2017中也无法编译。这三个我都是新建控制台项目，把sion.h加载进去，然后就会报语法错误。不知道是不是我的操作有问题，我等会用自己的电脑试试。

**Comment by zanllp** [comment]
专门下了vs2019，可以运行，乱码是因为编码错误。sion以前是用vs2017开发，本来是自带编码转换的。后面转向用Ubuntu+bazel+vscode就删除了
![image](https://user-images.githubusercontent.com/25872019/117449289-63c63a00-af72-11eb-8d82-13ad06666c04.png)

**Comment by Boreal** [comment]
> 专门下了vs2019，可以运行，乱码是因为编码错误。sion以前是用vs2017开发，本来是自带编码转换的。后面转向用Ubuntu+bazel+vscode就删除了
> ![image](https://user-images.githubusercontent.com/25872019/117449289-63c63a00-af72-11eb-8d82-13ad06666c04.png)

我也是在vs2019下运行，这个是编码问题吗，怎么解决呢
![image](https://user-images.githubusercontent.com/39616624/117457342-b6582400-af7b-11eb-8624-c0462348c380.png)
![image](https://user-images.githubusercontent.com/39616624/117457412-c4a64000-af7b-11eb-970f-1801f9e8bdbd.png)

**Comment by zanllp** [comment]
是编码问题，sion是从另外一个项目上分离出来的，那个项目用的vs2015默认多字节，现在变成unicode。改成多字节就行了
![image](https://user-images.githubusercontent.com/25872019/117460444-18feef00-af7f-11eb-8ff3-703dcc3828ba.png)

**Comment by Boreal** [comment]
> 是编码问题，sion是从另外一个项目上分离出来的，那个项目用的vs2015默认多字节，现在变成unicode。改成多字节就行了
> ![image](https://user-images.githubusercontent.com/25872019/117460444-18feef00-af7f-11eb-8ff3-703dcc3828ba.png)

终于在vs2019里面跑起来了，不止编码，我引用openssl也有问题，谢谢大佬指点啦
