### ISSUE TITLE
在Windows下编译失败

### ISSUE THREAD

**Issue by ntzxtyz** [zanllp/Sion#8]
输出诸如“未定义的标识符”“语法错误”“跳过明显的函数体”等。环境:MSVC 19.30.30401

**Comment by zanllp** [comment]
参考 #7 ，里面我使用vs2019和gcc是可以的

**Comment by ntzxtyz** [comment]
> 参考 #7 ，里面我使用vs2019和gcc是可以的

原来如此，谨受教了

**Comment by ntzxtyz** [comment]
> 参考 #7 ，里面我使用vs2019和gcc是可以的

在cmake项目里面如何配置项目属性呢？

**Comment by zanllp** [comment]
> > 参考 #7 ，里面我使用vs2019和gcc是可以的
> 
> 在cmake项目里面如何配置项目属性呢？

如果是在linux/mac下，参考https://github.com/zanllp/agumi 这个项目，他就使用到了sion。windows下的话我没试过用cmake编译

**Comment by zanllp** [comment]
你可以看下这个 https://docs.microsoft.com/zh-cn/cpp/build/reference/compiler-options?view=msvc-160

**Comment by ntzxtyz** [comment]
> 你可以看下这个 https://docs.microsoft.com/zh-cn/cpp/build/reference/compiler-options?view=msvc-160

多谢赐教。
