### ISSUE TITLE
异步请求的例子

### ISSUE THREAD

**Issue by lxc0916** [zanllp/Sion#9]
异步请求的例子没有了，是没有写吗？

**Comment by zanllp** [comment]
之前有的，如果是win的话可以直接用[example.cpp](https://github.com/zanllp/sion/blob/1b13c7d1bc69bafa99ea10b4368b4137fd2a10dc/src/example.cpp),
之前写跨平台时删除掉了。

后来的话我这边3个系统都用的是自己实现的事件循环队列+拓展过非阻塞api的sion，可以实现完全不阻塞的单线程请求，有点类似node那样的，不过那个太复杂，就没搞来这边。

想简单点可以直接搞个线程池，或者直接开个线程就像这样
```c++
#include "sion.h"
#include <fstream>
#include <thread>
#include <iostream>
#include <chrono>
void FetchFile(sion::String name)
{
    auto resp = sion::Fetch("http://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx");
    std::ofstream file(name, std::ios::binary);
    auto &bin = resp.BodyBin();
    file.write(bin.data(), bin.size());
}
int main()
{
    std::thread t_1([&]
                     { FetchFile("hello.jpeg"); });
    std::thread t_2([&]
                     { FetchFile("world.jpeg"); });
    t_1.join();
    t_2.join();
    return 1;
}
```

**Comment by lxc0916** [comment]
post请求测试过吗？感觉post请求会一直卡在第一次调用，调用成功后代码不会往下走了，也不报错

**Comment by zanllp** [comment]
![image](https://user-images.githubusercontent.com/25872019/139644443-5566c2b3-73fe-410b-b4fb-3ea783bc499e.png)
试了下没什么问题
```c++
#include "sion.h"
#include <fstream>
#include <thread>
#include <iostream>
#include <chrono>
void FetchFile(sion::String name)
{
    for (size_t i = 0; i < 3; i++)
    {
        auto resp = sion::Request()
                        .SetBody(R"({ "hello": "world" })")
                        .SetHeader("Content-type", "application/json")
                        .SetUrl("https://api.ioflow.link/socket/push?descriptor=IwPYC8kUSeUHDEdT")
                        .SetHttpMethod("POST")
                        .Send();
        std::cout << name << resp.Body() << std::endl;
    }
}
int main()
{
    std::thread t_1([&]
                    { FetchFile("hello.jpeg"); });
    std::thread t_2([&]
                    { FetchFile("world.jpeg"); });
    t_1.join();
    t_2.join();
    return 1;
}
```

**Comment by lxc0916** [comment]
void postlog(sion::String urlString,sion::String bodyString)
{

    try
		{
			auto resp =  sion::Request()
			.SetUrl(urlString)
			.SetHttpMethod(sion::Method::Post)
			.SetBody(bodyString)
			.SetHeader("Content-Type", "text/plain; charset=utf-8")
			.Send();
            cout << resp.Body() << endl;
		}
		catch (const std::exception & e)
		{
			cout << e.what();
		}
        
}
这样调应该是没问题的吧

**Comment by zanllp** [comment]
看起来没什么问题

**Comment by lxc0916** [comment]
.SetBody(R"({ "hello": "world" })")  这里这个字符串必须这样写吗？还是随便一个字符串就可以

**Comment by zanllp** [comment]
都可以的，这个R"(xxxx)"在c++里面表示原始字符串的意思，避免转义
```c++
R"({ "hello": "world" })";
"{ \"hello\": \"world\" })";
```
这两个是等价的

**Comment by zanllp** [comment]
已实现内置的异步请求 参考https://github.com/zanllp/sion#user-content-%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82
